### ISSUE TITLE
Support for 2019.3

### ISSUE THREAD

**Issue by nesl247** [Hiberbee/intellij-theme#10]
Just found this and realized it isn't compatible with 2019.3. Understandably so given that 2019.3 just released this week.

I'm not sure if there is anything needed other than updating the support versions or not.

**Comment by vladyslavvolkov** [comment]
Yep, just pushed new 1.4.0 version, should be available when JB verifies

https://plugins.jetbrains.com/plugin/12118-hiberbee-theme/versions

**Comment by nesl247** [comment]
Thanks for the quick update!
