### ISSUE TITLE
Which icon plugin do you use in screenshot

### ISSUE THREAD

**Issue by vunamhung** [Hiberbee/intellij-theme#3]
Hello,
I'm very like icon system in your screenshot, please tell me the name of plugin to do that.
Thank you.

**Comment by wassimseif** [comment]
https://plugins.jetbrains.com/plugin/10044-atom-material-icons/

**Comment by vladyslavvolkov** [comment]
@vunamhung Actually, this one https://plugins.jetbrains.com/plugin/12416-coderpillr-icons but it was inherited from material icons
