### ISSUE TITLE
background color and text merge

### ISSUE THREAD

**Issue by Paracells** [Hiberbee/intellij-theme#7]
![bug](https://user-images.githubusercontent.com/575811/61815810-b1cc8500-ae53-11e9-829d-c1da47408687.png)

**Comment by vladyslavvolkov** [comment]
@Paracells thanks, unfortunatelly I can't reproduce - done some fixes blindly - while plugin is approving by JB, could you check please if issue still persist - https://plugins.jetbrains.com/plugin/12118-hiberbee-theme/versions 1.3.2 version

**Comment by Paracells** [comment]
Now ok.. nice!
![Untitled](https://user-images.githubusercontent.com/575811/61930569-cfe6d200-af86-11e9-8a84-01d989cbaa6f.png)

**Comment by wassimseif** [comment]
@Paracells
I did have the problem you mentioned first & it was very annoying. ( PyCharm)
The latest update did change the color but it does not highlight the first row in this popup right ?

<img width="611" alt="Screen Shot 2019-07-26 at 5 38 21 PM" src="https://user-images.githubusercontent.com/7282773/61959492-2de9d880-afcc-11e9-99d1-a0233ed87ffd.png">

@vladyslavvolkov  is there any tutorial on how to build this theme ? Let's say i want to change the some colors, how can I apply it to my intellij instance
