### ISSUE TITLE
Breakpoint not visible 

### ISSUE THREAD

**Issue by wassimseif** [Hiberbee/intellij-theme#8]
Hello,

The small black point on line 10 is the breakpoint. Is this because of this theme ?

<img width="636" alt="Screen Shot 2019-08-06 at 7 32 28 PM" src="https://user-images.githubusercontent.com/7282773/62558101-0a067c80-b881-11e9-95e9-d0ef2267a47c.png">

**Comment by vladyslavvolkov** [comment]
Maybe. I've noticed that on breakpoint lines, sometimes. Will try to catch and fix, annoying
